"""remove lead_magnet_text

Revision ID: 2ee8c5d99db2
Revises: 1ec9967d6bd8
Create Date: 2026-06-10 11:57:53.474599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ee8c5d99db2'
down_revision: Union[str, Sequence[str], None] = '1ec9967d6bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funnel_settings', 'lead_magnet_file_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('funnel_settings', 'lead_magnet_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funnel_settings', sa.Column('lead_magnet_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('funnel_settings', 'lead_magnet_file_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
